# Generated by Django 5.2.7 on 2025-11-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_upload_processed_alter_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='processed',
        ),
        migrations.AddField(
            model_name='upload',
            name='state',
            field=models.CharField(choices=[('UP', 'Uploaded'), ('ST', 'Processing started'), ('DO', 'Done')], default='UP', max_length=2),
        ),
    ]
